### ISSUE TITLE
Upgrade to Laravel 5.6?

### ISSUE THREAD

**Issue by exfriend** [JackieDo/workbench#23]
This is incredibly useful package. I wonder if there are any difficulties / effort required to bump it up to 5.7?

**Comment by JackieDo** [comment]
> This is incredibly useful package. I wonder if there are any difficulties / effort required to bump it up to 5.7?

@exfriend: I'm sorry for not responding to your issue for quite a long time (because I need to rest after the illness). Now I can get back to work.

I have continued developing the package, and made a new branch for Laravel 5.6. You can see it [here](https://github.com/JackieDo/workbench/tree/5.6).

The issues you mentioned have been resolved with this [pull request](https://github.com/JackieDo/workbench/pull/25#issue-376321594). And I will do continue to upgrade this package for Laravel next versions.
